import { useState, useEffect } from 'react';
import './Companies.css';
import CompanyDetails from './CompanyDetails';

import tcsLogo from '../assets/Company-img/tcs.jpg';
import infosysLogo from '../assets/infosys.jpeg';
import accentureLogo from '../assets/accenture.png';
import capgeminiLogo from '../assets/capgemini.svg';
import wiproLogo from '../assets/wipro.png';
import cognizantLogo from '../assets/cognizant.png';
import cognizantOffice1 from '../assets/Company-img/Cognizant/cognizant_office_1.jpeg';
import cognizantOffice2 from '../assets/Company-img/Cognizant/cognizant_office_2.jpeg';
import cognizantOffice3 from '../assets/Company-img/Cognizant/cognizant_office_3.jpeg';
import microsoftLogo from '../assets/microsoft.png';
import deloitteLogo from '../assets/Company-img/Deloitte.jpg';
import kpmgLogo from '../assets/Company-img/kpmg.png';
import pwcLogo from '../assets/Company-img/pwc.png';
import ltLogo from '../assets/Company-img/L&T Infotech (LTIMindtree).jpg';
import tataMotorsLogo from '../assets/Company-img/tata_motors.jpg';
import siemensLogo from '../assets/Company-img/Siemens.png';
import boschLogo from '../assets/Company-img/bosch.jpg';
import hdfcLogo from '../assets/Company-img/HDFC Bank.jpg';
import iciciLogo from '../assets/Company-img/icici.jpg';
import goldmanSachsLogo from '../assets/Company-img/goldman_sachs.png';
import morganStanleyLogo from '../assets/Company-img/morgan_stanley.jpg';
import muSigmaLogo from '../assets/Company-img/mu_sigma.jpg';
import fractalLogo from '../assets/Company-img/fractal_analytics.png';
import latentViewLogo from '../assets/Company-img/latentview.png';
import jioLogo from '../assets/Company-img/jio.jpg';
import airtelLogo from '../assets/Company-img/airtel.png';
import jaroLogo from '../assets/Company-img/jaro_education.png';
import byjusLogo from '../assets/Company-img/byjus.png';
import amazonLogo from '../assets/Company-img/amazon.png';
import googleLogo from '../assets/google.jpeg';
import sapLogo from '../assets/sap.jpg';
import ibmLogo from '../assets/Company-img/ibm.png';
import oracleLogo from '../assets/Company-img/Oracle.png';

import accentureOffice1 from '../assets/Company-img/Accenture/accenture_office_1.png';
import accentureOffice2 from '../assets/Company-img/Accenture/accenture_office_2.jpg';
import accentureOffice3 from '../assets/Company-img/Accenture/accenture_office_3.jpg';
import capgeminiOffice1 from '../assets/Company-img/Capgemini/capgemini_office_1.png';
import capgeminiOffice2 from '../assets/Company-img/Capgemini/capgemini_office_2.jpg';
import capgeminiOffice3 from '../assets/Company-img/Capgemini/capgemini_office_3.jpg';
import deloitteOffice1 from '../assets/Company-img/Deloitte/deloitte_office_1.jpg';
import deloitteOffice2 from '../assets/Company-img/Deloitte/deloitte_office_2.png';
import deloitteOffice3 from '../assets/Company-img/Deloitte/deloitte_office_3.png';
import googleOffice1 from '../assets/Company-img/Google/google_office_1.jpg';
import googleOffice2 from '../assets/Company-img/Google/google_office_2.jpg';
import googleOffice3 from '../assets/Company-img/Google/google_office_3.png';
import infosysOffice1 from '../assets/Company-img/Infosys/infosys_office_1.jpg';
import infosysOffice2 from '../assets/Company-img/Infosys/infosys_office_2.png';
import infosysOffice3 from '../assets/Company-img/Infosys/infosys_office_3.png';
import kpmgOffice1 from '../assets/Company-img/KPMG/kpmg_office_1.png';
import kpmgOffice2 from '../assets/Company-img/KPMG/kpmg_office_2.jpeg';
import kpmgOffice3 from '../assets/Company-img/KPMG/kpmg_office_3.jpg';
import ltOffice1 from '../assets/Company-img/L&T/lt_office_1.jpg';
import ltOffice2 from '../assets/Company-img/L&T/lt_office_2.jpg';
import ltOffice3 from '../assets/Company-img/L&T/lt_office_3.png';
import microsoftOffice1 from '../assets/Company-img/Microsoft/microsoft_office_1.jpg';
import microsoftOffice2 from '../assets/Company-img/Microsoft/microsoft_office_2.jpg';
import microsoftOffice3 from '../assets/Company-img/Microsoft/microsoft_office_3.jpg';
import pwcOffice1 from '../assets/Company-img/PwC/pwc_office_1.jpg';
import pwcOffice2 from '../assets/Company-img/PwC/pwc_office_2.jpg';
import pwcOffice3 from '../assets/Company-img/PwC/pwc_office_3.jpg';
import sapOffice1 from '../assets/Company-img/SAP/sap_office_1.jpg';
import sapOffice2 from '../assets/Company-img/SAP/sap_office_2.jpg';
import sapOffice3 from '../assets/Company-img/SAP/sap_office_3.jpg';
import siemensOffice1 from '../assets/Company-img/Siemens/siemens_office_1.jpg';
import siemensOffice2 from '../assets/Company-img/Siemens/siemens_office_2.jpg';
import siemensOffice3 from '../assets/Company-img/Siemens/siemens_office_3.jpg';
import tatamotorsOffice1 from '../assets/Company-img/TataMotors/tatamotors_office_1.jpg';
import tatamotorsOffice2 from '../assets/Company-img/TataMotors/tatamotors_office_2.jpg';
import tatamotorsOffice3 from '../assets/Company-img/TataMotors/tatamotors_office_3.jpg';
import tcsOffice1 from '../assets/Company-img/TCS/tcs_office_1.png';
import tcsOffice2 from '../assets/Company-img/TCS/tcs_office_2.png';
import tcsOffice3 from '../assets/Company-img/TCS/tcs_office_3.jpg';
import wiproOffice1 from '../assets/Company-img/Wipro/wipro_office_1.jpeg';
import wiproOffice2 from '../assets/Company-img/Wipro/wipro_office_2.jpg';
import wiproOffice3 from '../assets/Company-img/Wipro/wipro_office_3.jpg';

import boschOffice1 from '../assets/Company-img/Bosch/bosch_office_1.jpg';
import boschOffice2 from '../assets/Company-img/Bosch/bosch_office_2.jpg';
import boschOffice3 from '../assets/Company-img/Bosch/bosch_office_3.jpg';

import hdfcOffice1 from '../assets/Company-img/HDFCBank/hdfcbank_office_1.jpg';
import hdfcOffice2 from '../assets/Company-img/HDFCBank/hdfcbank_office_2.jpg';
import hdfcOffice3 from '../assets/Company-img/HDFCBank/hdfcbank_office_3.jpg';

import iciciOffice1 from '../assets/Company-img/ICICIBank/icicibank_office_1.jpg';
import iciciOffice2 from '../assets/Company-img/ICICIBank/icicibank_office_2.jpg';
import iciciOffice3 from '../assets/Company-img/ICICIBank/icicibank_office_3.jpg';

import gsOffice1 from '../assets/Company-img/GoldmanSachs/goldmansachs_office_1.jpg';
import gsOffice2 from '../assets/Company-img/GoldmanSachs/goldmansachs_office_2.jpg';
import gsOffice3 from '../assets/Company-img/GoldmanSachs/goldmansachs_office_3.jpg';

import morganOffice1 from '../assets/Company-img/MorganStanley/morganstanley_office_1.jpg';
import morganOffice2 from '../assets/Company-img/MorganStanley/morganstanley_office_2.jpg';
import morganOffice3 from '../assets/Company-img/MorganStanley/morganstanley_office_3.jpg';


import Navbar from './Navbar';

const officeImagesPlaceholder = [
  'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
  'https://images.unsplash.com/photo-1572025442646-866d16c84a54?auto=format&fit=crop&w=600&q=80',
  'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=600&q=80'
];

export const COMPANIES = [
  // IT & Software
  { id: 1, name: 'TCS', fullName: 'Tata Consultancy Services', category: 'it', sector: 'IT & Software', location: 'Mumbai, Maharashtra', logo: tcsLogo, website: 'https://www.tcs.com', startedFrom: '1968', founder: 'J. R. D. Tata & F. C. Kohli', employees: '614,000+', workCulture: 'Innovation, Integrity, Excellence', studentsPlaced: '1200+ (Approx.)', description: 'TCS is an Indian multinational information technology services and consulting company.', moreInfo: `Tata Consultancy Services (TCS) is an Indian multinational information technology (IT) services and consulting company headquartered in Mumbai, Maharashtra. Founded in 1968 by the Tata Group, TCS operates in 150 locations across 46 countries, making it one of the largest IT service brands worldwide. The company provides a wide range of services including application development, enterprise software, consulting, and business process outsourcing. TCS is well-known for its massive scale, robust innovation ecosystems, and strong commitment to technological advancements across multiple industries, including banking, healthcare, retail, and manufacturing.

TCS has continually been ranked as one of the most valuable IT services brands globally. The company heavily invests in research and development, particularly in emerging fields such as artificial intelligence, machine learning, cloud computing, blockchain, and cybersecurity through its extensive TCS Research and Innovation division. Beyond its technological prowess, TCS is deeply committed to corporate social responsibility, focusing extensively on education, environmental sustainability, and large-scale community development. With a massive global workforce of over 600,000 highly skilled professionals, TCS fosters a culture of continuous learning, diversity, and inclusion. The company’s flagship platforms, such as TCS BaNCS for financial services and TCS IGNIO for cognitive automation, serve as the digital backbone for countless organizations. By partnering with global enterprises, TCS accelerates digital transformation journeys, helping businesses optimize operations, enhance customer experiences, and navigate complex market landscapes effectively.`, officeImages: [tcsOffice1, tcsOffice2, tcsOffice3] },
  { id: 2, name: 'Infosys', fullName: 'Infosys Limited', category: 'it', sector: 'IT & Software', location: 'Bengaluru, Karnataka', logo: infosysLogo, website: 'https://www.infosys.com', startedFrom: '1981', founder: 'N.R. Narayana Murthy', employees: '322,000+', workCulture: 'Continuous Learning, Respect, Integrity', studentsPlaced: '800+ (Approx.)', description: 'Infosys is a global leader in next-generation digital services and consulting.', moreInfo: 'Infosys Limited is a leading Indian multinational company that provides information technology (IT), consulting, outsourcing, and digital transformation services. Founded in 1981 and headquartered in Bengaluru, Karnataka, the company has grown into one of the world\'s largest IT service providers. Infosys offers a wide range of services, including software development, cloud computing, artificial intelligence (AI), data analytics, cybersecurity, enterprise application development, and business process management. It serves clients across industries such as banking, healthcare, manufacturing, retail, telecommunications, energy, and insurance, helping organizations improve efficiency and adopt modern digital technologies.\n\nInfosys has a global presence with offices and development centers in more than 50 countries, serving clients worldwide. The company is recognized for its focus on innovation, sustainability, employee training, and high-quality service delivery. Through platforms like Infosys Topaz (AI-powered solutions) and its digital transformation services, the company enables businesses to automate processes, enhance customer experiences, and make data-driven decisions. Infosys is also known for its strong corporate governance, commitment to environmental sustainability, and continuous investment in research, development, and workforce upskilling, making it one of the most respected IT companies globally.', officeImages: [infosysOffice1, infosysOffice3, infosysOffice2] },
  { id: 3, name: 'Capgemini', fullName: 'Capgemini SE', category: 'it', sector: 'IT & Software', location: 'Paris, France', logo: capgeminiLogo, website: 'https://www.capgemini.com', startedFrom: '1967', founder: 'Serge Kampf', employees: '340,000+', workCulture: 'Boldness, Trust, Freedom', studentsPlaced: '950+ (Approx.)', description: 'Capgemini is a global leader in partnering with companies to transform and manage their business by harnessing the power of technology.', moreInfo: `Capgemini SE is a French multinational information technology services and consulting company headquartered in Paris, France. Founded in 1967 by Serge Kampf, it has grown organically and through strategic acquisitions to become a global leader in partnering with companies to transform and manage their business. Capgemini offers deep industry expertise combined with command of the rapidly evolving fields of cloud computing, data analytics, artificial intelligence, software development, and digital platforms. The company serves a wide spectrum of industries, delivering end-to-end solutions that help organizations modernize their IT infrastructure, improve operational efficiency, and drive sustainable growth in a competitive global market.

Guided by its core purpose of unleashing human energy through technology for an inclusive and sustainable future, Capgemini places a strong emphasis on sustainability, diversity, and digital inclusion. The organization operates through several specialized sub-brands, including Capgemini Invent for strategy and transformation, and Capgemini Engineering for specialized engineering and R&D services. With a massive workforce of over 340,000 employees distributed across more than 50 countries, the company fosters a deeply entrepreneurial culture built on boldness, trust, and freedom. Capgemini continues to pioneer digital innovation, enabling enterprises to navigate complex technological shifts, adopt intelligent industry solutions, and achieve long-term resilience. The company's comprehensive portfolio of services ensures that clients can seamlessly integrate cutting-edge technologies to enhance their operational capabilities and deliver superior customer experiences.`, officeImages: [capgeminiOffice1, capgeminiOffice2, capgeminiOffice3] },
  { id: 4, name: 'Wipro', fullName: 'Wipro Limited', category: 'it', sector: 'IT & Software', location: 'Bengaluru, Karnataka', logo: wiproLogo, website: 'https://www.wipro.com', startedFrom: '1945', founder: 'M.H. Hasham Premji', employees: '240,000+', workCulture: 'Inclusion, Empathy, Customer First', studentsPlaced: '700+ (Approx.)', description: 'Wipro is a leading technology services and consulting company focused on building innovative solutions.', moreInfo: `Wipro Limited is a leading Indian multinational corporation that provides comprehensive information technology, consulting, and business process services. Founded in 1945 by M.H. Hasham Premji, the company originally started as a manufacturer of vegetable and refined oils before making a visionary pivot to the IT industry in the 1980s, thereby becoming a pioneering force in India's technology boom. Today, Wipro leverages its holistic portfolio of capabilities in consulting, design, engineering, and operations to help clients realize their boldest ambitions. The company offers a wide array of services including cloud computing, cybersecurity, digital transformation, artificial intelligence, data analytics, and robotics, catering to critical sectors like healthcare, banking, retail, manufacturing, and energy.

Wipro is widely recognized for its extensive global portfolio of services, deep domain expertise, and a strong, unwavering commitment to sustainability and active corporate citizenship. The company operates globally with a vast workforce of over 240,000 professionals dedicated to delivering innovative solutions and enhancing customer experiences across six continents. Through strategic initiatives and robust technology partnerships, Wipro continuously adapts to the dynamic technological landscape, ensuring that its clients remain competitive, agile, and future-ready. Furthermore, the Azim Premji Foundation, which is inextricably linked to Wipro's legacy, drives significant philanthropic efforts in education, healthcare, and social development in India, reflecting the company's deeply ingrained ethos of giving back to society and fostering inclusive, equitable growth for all.`, officeImages: [wiproOffice1, wiproOffice2, wiproOffice3] },
  { id: 5, name: 'Cognizant', fullName: 'Cognizant Technology Solutions', category: 'it', sector: 'IT & Software', location: 'Teaneck, USA', logo: cognizantLogo, website: 'https://www.cognizant.com', startedFrom: '1994', founder: 'Kumar Mahadeva', employees: '350,000+', workCulture: 'Collaboration, Transparency, Empowerment', studentsPlaced: '850+ (Approx.)', description: 'Cognizant engineers modern businesses to improve everyday life.', moreInfo: `Cognizant Technology Solutions is an American multinational information technology services and consulting company headquartered in Teaneck, New Jersey. Founded in 1994 as an in-house technology unit of The Dun & Bradstreet Corporation, Cognizant has rapidly grown into one of the world's most prominent digital transformation and IT services providers. The company helps clients modernize technology, reimagine processes, and transform experiences so they can stay ahead in a fast-changing, hyper-competitive world. Cognizant specializes in advanced areas such as digital strategy, the Internet of Things (IoT), artificial intelligence, software engineering, and cloud enablement, serving key global industries including healthcare, financial services, communications, media, and consumer goods.

Consistently ranked amongst the most admired and fastest-growing companies globally, Cognizant delivers deep industry expertise and robust technology solutions tailored to the unique operational needs of its clients. The company’s unique global delivery model and deeply ingrained client-centric approach have been central to its consistent growth, industry leadership, and strong market positioning. Cognizant is heavily invested in continuously upskilling its workforce and fostering an inclusive, diverse workplace culture that encourages innovation and agile problem-solving. By expanding its digital capabilities through strategic acquisitions and building strong partnerships with leading technology vendors, Cognizant enables modern businesses to effectively navigate digital disruptions, optimize their core operations, and dramatically improve everyday life for millions of end-users worldwide.`, officeImages: [cognizantOffice1, cognizantOffice2, cognizantOffice3] },
  { id: 6, name: 'Google', fullName: 'Google LLC', category: 'it', sector: 'IT & Software', location: 'Mountain View, USA', logo: googleLogo, website: 'https://about.google', startedFrom: '1998', founder: 'Larry Page & Sergey Brin', employees: '180,000+', workCulture: 'Creativity, Openness, Innovation', studentsPlaced: '50+ (Premium)', description: 'Google specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware.', moreInfo: `Google LLC is an American multinational corporation and technology giant focusing extensively on online advertising, search engine technology, cloud computing, computer software, e-commerce, consumer electronics, and artificial intelligence. Founded in 1998 by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University, Google has evolved from a simple algorithmic search engine into a global technological behemoth. The company offers a vast, interconnected ecosystem of products and services, including Google Workspace, the Android mobile operating system, Google Cloud, and hardware devices like the Pixel smartphones and Nest smart home products. Google's foundational mission is to organize the world's information and make it universally accessible and useful, a visionary goal that drives its continuous innovation.

Widely renowned for its vibrant, innovative work culture, massive global scale, and incredibly robust technological infrastructure, Google remains one of the most powerful and influential technology companies in the world today. The company stands at the absolute forefront of artificial intelligence research, developing cutting-edge AI models, such as Gemini, and integrating them seamlessly across its entire product suite to enhance user experiences. Google is also deeply committed to operating sustainably, boldly aiming to run its entire global operations on carbon-free energy by 2030. With a workforce composed of some of the brightest engineering minds in the industry, Google continues to push the boundaries of what is technologically possible, fundamentally shaping human interaction with technology.`, officeImages: [googleOffice1, googleOffice2, googleOffice3] },
  { id: 7, name: 'Microsoft', fullName: 'Microsoft Corporation', category: 'it', sector: 'IT & Software', location: 'Redmond, USA', logo: microsoftLogo, website: 'https://www.microsoft.com', startedFrom: '1975', founder: 'Bill Gates & Paul Allen', employees: '220,000+', workCulture: 'Growth Mindset, Diversity, Inclusion', studentsPlaced: '60+ (Premium)', description: 'Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge.', moreInfo: `Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington. Established by Bill Gates and Paul Allen in 1975, it is universally recognized for its ubiquitous Windows operating systems, the comprehensive Microsoft Office productivity suite, and its influential web browsers. Over the past several decades, Microsoft has successfully and aggressively transitioned from a purely software-centric company to a dominant global force in cloud computing, enterprise services, artificial intelligence, and hardware. The company’s flagship cloud platform, Microsoft Azure, alongside its pervasive enterprise solutions, serves as the critical digital backbone for millions of businesses, governments, and educational institutions worldwide, driving immense operational efficiency and enabling profound digital transformation.

Microsoft's core mission is to empower every person and every organization on the planet to achieve more. The company has aggressively expanded into the realm of artificial intelligence, significantly investing in advanced AI research, partnering with OpenAI, and integrating intelligent capabilities—such as Microsoft Copilot—across its entire massive product portfolio. Microsoft is also a major player in the global gaming industry through its Xbox brand and maintains a very strong organizational focus on accessibility and inclusive design. Furthermore, the company is deeply committed to environmental sustainability, officially pledging to be entirely carbon negative by 2030. With a diverse global workforce and a culture centered around a growth mindset, Microsoft continues to architect the modern digital era.`, officeImages: [microsoftOffice1, microsoftOffice2, microsoftOffice3] },
  { id: 8, name: 'SAP', fullName: 'SAP SE', category: 'it', sector: 'IT & Software', location: 'Walldorf, Germany', logo: sapLogo, website: 'https://www.sap.com', startedFrom: '1972', founder: 'Dietmar Hopp', employees: '105,000+', workCulture: 'Customer Focus, Quality, Integrity', studentsPlaced: '120+ (Approx.)', description: 'SAP is a market leader in enterprise application software, helping companies of all sizes run at their best.', moreInfo: `SAP SE is a German multinational software company based in Walldorf, Baden-Württemberg. Founded in 1972 by five former IBM engineers, it primarily develops enterprise software to manage business operations and customer relations, famously establishing the global standard for enterprise resource planning (ERP) systems. SAP helps companies of all sizes and across all industries run at their absolute best, producing robust solutions that streamline and automate complex processes across finance, human resources, supply chain, procurement, and manufacturing. The company’s extremely comprehensive suite of applications and services enables businesses to operate profitably, adapt continuously, and grow sustainably in an increasingly dynamic and highly competitive global marketplace.

Today, SAP leverages cutting-edge technologies such as advanced machine learning, the Internet of Things (IoT), and highly sophisticated data analytics to turn customers' businesses into highly intelligent, resilient, and data-driven operations. With a vast global partner network and a massive customer base that includes the vast majority of the world's top corporations, SAP stands as a central, indispensable pillar of global commerce. The company is also intensely focused on sustainability and corporate social responsibility, proactively helping its clients track, analyze, and significantly reduce their carbon footprints through innovative software solutions. SAP's unwavering commitment to continuous technological innovation and exceptional customer success ensures its enduring, dominant leadership position within the global enterprise application software domain.`, officeImages: [sapOffice1, sapOffice2, sapOffice3] },

  // Consulting
  { id: 9, name: 'Accenture', fullName: 'Accenture plc', category: 'consulting', sector: 'Consulting', location: 'Dublin, Ireland', logo: accentureLogo, website: 'https://www.accenture.com', startedFrom: '1989', founder: 'Clarence DeLany', employees: '730,000+', workCulture: 'Client Value Creation, Respect', studentsPlaced: '1500+ (Approx.)', description: 'Accenture is a global professional services company with leading capabilities in digital, cloud and security.', moreInfo: `Accenture plc is a Dublin-based multinational professional services company specializing in broad information technology services and strategic consulting. Founded originally as the business and technology consulting division of Arthur Andersen, it became an independent entity in 1989 and has since grown organically and through acquisitions into a massive global powerhouse. Accenture offers a highly comprehensive range of services across five main areas: Strategy and Consulting, Technology, Operations, Industry X, and Accenture Song (its digital agency services). The company partners closely with many of the world's leading businesses, governments, and diverse organizations, helping them navigate incredibly complex digital transformations, optimize their core operations, and accelerate sustainable, long-term growth.

Combining unmatched global experience and highly specialized skills across more than 40 diverse industries, Accenture operates effectively at the critical intersection of business and advanced technology. The company is heavily invested in emerging technological frontiers such as artificial intelligence, generative AI, cloud computing, and advanced cybersecurity, continually training its massive workforce of over 730,000 professionals to stay well ahead of the technology curve. Accenture is also widely recognized and highly awarded for its strong organizational commitment to inclusion, workplace diversity, and environmental sustainability, striving constantly to create 360-degree value for all its stakeholders. With a formidable global footprint, Accenture consistently delivers highly innovative solutions that drive tangible, transformational business outcomes worldwide.`, officeImages: [accentureOffice1, accentureOffice2, accentureOffice3] },
  { id: 10, name: 'Deloitte', fullName: 'Deloitte Touche Tohmatsu Limited', category: 'consulting', sector: 'Consulting', location: 'London, UK', logo: deloitteLogo, website: 'https://www.deloitte.com', startedFrom: '1845', founder: 'William Welch Deloitte', employees: '415,000+', workCulture: 'Leadership, Collaboration, Quality', studentsPlaced: '400+ (Approx.)', description: 'Deloitte provides audit, consulting, financial advisory, risk advisory, tax and related services to select clients.', moreInfo: `Deloitte Touche Tohmatsu Limited, commonly referred to simply as Deloitte, is an expansive international professional services network headquartered in London, UK. Recognized globally as one of the prestigious Big Four accounting organizations, its rich history dates back to 1845 when William Welch Deloitte opened his first office in London. Today, Deloitte offers industry-leading audit and assurance, consulting, financial advisory, risk advisory, and tax services to many of the world’s most admired and valuable brands, including a significant majority of the Fortune Global 500 companies. The firm operates across multiple complex industry sectors, providing bespoke, highly tailored solutions that help clients overcome complex business challenges, ensure strict regulatory compliance, and achieve their strategic corporate objectives.

Deloitte comprises hundreds of thousands of dedicated professionals operating seamlessly in a globally connected network of member firms spanning over 150 countries and territories. The organization is deeply committed to making an impact that matters, leveraging its incredibly expansive industry knowledge and deep technical expertise to drive corporate success and broader societal progress. Deloitte is also actively at the forefront of digital transformation, actively advising top-tier clients on the strategic integration of artificial intelligence, blockchain, cloud technologies, and advanced data analytics. With a tremendously strong culture of leadership, continuous learning, and ethical integrity, Deloitte continues to be a highly trusted strategic advisor to global enterprises.`, officeImages: [deloitteOffice1, deloitteOffice2, deloitteOffice3] },
  { id: 11, name: 'KPMG', fullName: 'KPMG International Limited', category: 'consulting', sector: 'Consulting', location: 'Amstelveen, Netherlands', logo: kpmgLogo, website: 'https://home.kpmg', startedFrom: '1987', founder: 'Piet Klijnveld', employees: '265,000+', workCulture: 'Integrity, Excellence, Courage', studentsPlaced: '250+ (Approx.)', description: 'KPMG is a global network of professional firms providing Audit, Tax and Advisory services.', moreInfo: `KPMG International Limited is one of the globally recognized Big Four accounting organizations, prominently headquartered in Amstelveen, Netherlands. Formed in 1987 through the major merger of Peat Marwick International and Klynveld Main Goerdeler, KPMG has firmly established itself as a premier global network of professional services firms. The organization provides incredibly comprehensive Audit, Tax, and Advisory services, catering to large multinational corporations, governments, and public-sector agencies worldwide. KPMG is deeply dedicated to helping its diverse clients mitigate complex risks, heavily optimize their financial performance, and capitalize on new, emerging market opportunities through rigorous financial analysis, deep industry insights, and highly innovative, tailored business solutions.

Operating extensively in over 140 countries and territories, KPMG leverages a highly robust and expansive network of independent member firms to offer globally coordinated yet intricately locally nuanced services. The firm prioritizes professional integrity, exceptional quality, and the rapid, strategic adoption of emerging technologies—such as artificial intelligence, automation, and advanced data analytics—to dramatically enhance its service delivery capabilities. KPMG is also strongly and consistently committed to active corporate citizenship, focusing heavily on global initiatives related to education, lifelong learning, and environmental sustainability. By fostering a strong culture of excellence and deeply empowering its vast workforce of professionals, KPMG consistently delivers high-quality outcomes that build immense trust.`, officeImages: [kpmgOffice1, kpmgOffice2, kpmgOffice3] },
  { id: 12, name: 'PwC', fullName: 'PricewaterhouseCoopers', category: 'consulting', sector: 'Consulting', location: 'London, UK', logo: pwcLogo, website: 'https://www.pwc.com', startedFrom: '1998', founder: 'Samuel Lowell Price', employees: '328,000+', workCulture: 'Care, Teamwork, Challenge', studentsPlaced: '300+ (Approx.)', description: 'PwC is a multinational professional services network, ranking as the second-largest professional services network in the world.', moreInfo: `PricewaterhouseCoopers (commonly known as PwC) is a massive multinational professional services network, currently ranking as the second-largest professional services network in the world and firmly established as one of the elite Big Four accounting firms. Formed in 1998 by the strategic merger of Coopers & Lybrand and Price Waterhouse, the firm boasts a very rich heritage and an extraordinarily massive global presence. PwC provides a wide, comprehensive array of services including audit and assurance, sophisticated tax consulting, and strategic management consulting to a vast global clientele ranging from massive multinational corporations to dynamic private businesses. The firm excels immensely in helping organizations navigate complex, ever-changing regulatory environments, manage enterprise risks, and implement strategic transformations.

PwC's fundamental core purpose is to build deep trust in society and effectively solve highly important, complex problems. Their tremendously expansive footprint allows them to offer highly diverse expertise and bring highly innovative, cross-functional perspectives to help corporate clients overcome modern, multifaceted business challenges. PwC is currently investing heavily in large-scale digital upskilling and the deep integration of artificial intelligence, cloud infrastructure, and cybersecurity solutions directly into its core consulting practice. The organization is also deeply committed to environmental sustainability and workplace inclusion, striving constantly to create a massively positive societal impact through its strategic global "The New Equation" business strategy.`, officeImages: [pwcOffice1, pwcOffice2, pwcOffice3] },

  // Core Engineering
  { id: 13, name: 'L&T', fullName: 'Larsen & Toubro', category: 'core', sector: 'Core Engineering', location: 'Mumbai, Maharashtra', logo: ltLogo, website: 'https://www.larsentoubro.com', startedFrom: '1938', founder: 'Henning Holck-Larsen', employees: '337,000+', workCulture: 'Discipline, Safety, Quality', studentsPlaced: '150+ (Approx.)', description: 'L&T is an Indian multinational conglomerate company, with business interests in engineering, construction, manufacturing, technology.', moreInfo: `Larsen & Toubro Ltd (L&T) is an Indian multinational conglomerate with principal business interests heavily concentrated in engineering, construction, manufacturing, technology, and financial services. Founded in 1938 by two Danish engineers who sought refuge in India, it has grown over the decades to become deeply, inextricably integrated into the nation's core infrastructure and industrial backbone. L&T is actively and prominently involved in executing some of the most complex, large-scale, and technologically challenging engineering and construction projects globally, spanning critical sectors like heavy civil infrastructure, power, hydrocarbon, and advanced defense. The company's highly specialized heavy engineering division manufactures intricate, massive equipment for refineries, petrochemical plants, and nuclear power sectors, showcasing its immense, unparalleled technical engineering prowess.

A strong, customer-focused approach and a constant, unwavering quest for top-class, world-leading quality have enabled L&T to attain and sustain leadership in its major lines of business over the decades. The company is fundamentally characterized by an incredibly strong organizational culture of strict discipline, paramount safety, and technological innovation, continuously adopting and integrating advanced digital technologies to drastically enhance project execution and overall operational efficiency. L&T also places a very high strategic priority on environmental, social, and governance (ESG) practices, contributing significantly to widespread community development and pioneering green energy initiatives. With a vast, highly skilled workforce and a massive global footprint, L&T remains a genuine powerhouse of engineering excellence.`, officeImages: [ltOffice1, ltOffice2, ltOffice3] },
  { id: 14, name: 'Tata Motors', fullName: 'Tata Motors Limited', category: 'core', sector: 'Core Engineering', location: 'Pune, Maharashtra', logo: tataMotorsLogo, website: 'https://www.tatamotors.com', startedFrom: '1945', founder: 'J. R. D. Tata', employees: '78,000+', workCulture: 'Pioneering, Responsibility', studentsPlaced: '80+ (Approx.)', description: 'Tata Motors Limited is a leading global automobile manufacturer, a part of the Tata Group.', moreInfo: `Tata Motors Limited is a globally renowned, leading automobile manufacturer and a highly prominent, flagship part of the illustrious, historically significant Tata Group. Founded in 1945, the company designs, develops, and produces a wonderfully diverse and highly comprehensive portfolio of vehicles, ranging from compact passenger cars and premium sports utility vehicles to heavy commercial trucks, buses, and highly specialized defense vehicles. Tata Motors has been fundamentally instrumental in shaping and driving the entire Indian automotive industry, consistently introducing highly innovative mobility solutions tailored meticulously to the unique, demanding needs of diverse, rapidly growing markets. The company maintains a massive, sprawling international presence through its various subsidiaries and strategic joint ventures, most notably including the prestigious, world-renowned British luxury carmaker Jaguar Land Rover.

Deeply driven by a powerful organizational mission to connect human aspirations, Tata Motors focuses extremely heavily on cutting-edge research, advanced development, and sweeping technological innovation. The company has aggressively and successfully expanded into the rapidly growing electric vehicle (EV) segment, pioneering EV commercialization in India and publicly committing to highly sustainable, zero-emission future mobility solutions. Tata Motors operates several state-of-the-art, highly automated manufacturing facilities and advanced R&D centers across the globe, ensuring the absolute highest standards of manufacturing quality, vehicle safety, and driving performance. Consistently committed to broad corporate social responsibility and deep environmental sustainability, Tata Motors continues to boldly lead the transition towards much smarter, considerably safer, and significantly greener mobility worldwide.`, officeImages: [tatamotorsOffice3, tatamotorsOffice1, tatamotorsOffice2] },
  { id: 15, name: 'Siemens', fullName: 'Siemens India', category: 'core', sector: 'Core Engineering', location: 'Mumbai, Maharashtra', logo: siemensLogo, website: 'https://www.siemens.com', startedFrom: '1847', founder: 'Werner von Siemens', employees: '311,000+', workCulture: 'Responsible, Excellent, Innovative', studentsPlaced: '90+ (Approx.)', description: 'Siemens is a technology company focused on industry, infrastructure, transport, and healthcare.', moreInfo: `Siemens is a massive German multinational conglomerate corporation and unequivocally the largest industrial manufacturing company in all of Europe. Headquartered in Munich, Siemens was originally founded in 1847 by Werner von Siemens and Johann Georg Halske, initially operating modestly as a telegraph company. Today, Siemens operates extensively globally across deeply integrated, highly specialized divisions focusing intensely on industry, infrastructure, transport, and advanced healthcare. The company is a major, driving technological force behind the Fourth Industrial Revolution (Industry 4.0), providing incredibly advanced automation, broad electrification, and comprehensive digitalization solutions that massively optimize complex manufacturing processes, significantly improve energy efficiency, and thoroughly modernize urban infrastructure worldwide.

By continually and seamlessly combining the real, physical world with the advanced digital world, Siemens actively empowers its vast customer base to completely transform their respective markets and industries. The company holds a truly massive, unparalleled global portfolio of advanced software, electrical, and digital engineering technologies, while simultaneously heavily investing in bleeding-edge research areas like artificial intelligence, digital twins, and highly secure industrial cybersecurity. Siemens is deeply and structurally committed to environmental sustainability, officially aiming to achieve a complete net-zero carbon footprint and actively helping its clients do exactly the same through incredibly innovative green technologies. With a truly vast global workforce composed of tens of thousands of dedicated engineers, Siemens remains firmly at the absolute forefront of global technological advancement.`, officeImages: [siemensOffice1, siemensOffice2, siemensOffice3] },
  { id: 16, name: 'Bosch', fullName: 'Bosch India', category: 'core', sector: 'Core Engineering', location: 'Bengaluru, Karnataka', logo: boschLogo, website: 'https://www.bosch.in', startedFrom: '1886', founder: 'Robert Bosch', employees: '421,000+', workCulture: 'Fairness, Reliability, Agility', studentsPlaced: '110+ (Approx.)', description: 'Bosch represents a worldwide network of products and services spanning mobility, consumer goods, industry.', moreInfo: `Robert Bosch GmbH, universally known simply as Bosch, is a massive German multinational engineering and technology company headquartered in Gerlingen. Founded in 1886 by visionary inventor Robert Bosch, the company has successfully evolved over a century into a leading, highly dominant global supplier of advanced technology and services, spanning comprehensive mobility solutions, industrial technology, consumer goods, and energy and building technology. Bosch is incredibly deeply embedded in the global automotive industry, serving proudly as one of the world's absolute largest suppliers of critical automotive components and being extremely deeply involved in the cutting-edge development of highly automated driving, vehicle electrification, and advanced vehicle connectivity. Beyond the massive automotive sector, Bosch manufactures incredibly high-quality power tools, household appliances, and highly advanced industrial manufacturing machinery.

The company's overarching strategic objective is to continuously deliver technological solutions for a fully connected life, significantly and tangibly improving global quality of life with deeply innovative and widely accessible products. Bosch currently operates under a highly unique corporate ownership structure, with a massive charitable foundation holding the vast majority of its shares, thereby ensuring that the company remains completely independent and highly focused on long-term sustainability rather than short-term profits. Bosch is a recognized global pioneer in the Internet of Things (IoT) and artificial intelligence, seamlessly integrating these technologies into its vast product ecosystem. Bosch continues to engineer smart technologies that are truly "Invented for life."`, officeImages: [boschOffice1, boschOffice2, boschOffice3] },

  // Finance
  { id: 17, name: 'HDFC Bank', fullName: 'HDFC Bank Limited', category: 'finance', sector: 'Finance', location: 'Mumbai, Maharashtra', logo: hdfcLogo, website: 'https://www.hdfcbank.com', startedFrom: '1994', founder: 'Hasmukhbhai Parekh', employees: '177,000+', workCulture: 'Trust, Transparency, Customer Focus', studentsPlaced: '300+ (Approx.)', description: 'HDFC Bank is India’s leading private sector bank offering a wide range of financial products and services.', moreInfo: `HDFC Bank Limited is a tremendously premier Indian banking and financial services company headquartered prominently in Mumbai. Incorporated relatively recently in 1994, it stands incredibly today as India's absolute largest private sector bank by total assets and overall market capitalization, proudly serving many tens of millions of retail and corporate customers across the nation. The bank offers a remarkably comprehensive suite of modern banking products and advanced financial services, deeply encompassing retail banking, wholesale banking, massive treasury operations, and highly innovative digital financial solutions. HDFC Bank has played an absolutely pivotal, foundational role in thoroughly modernizing the entire Indian banking sector, aggressively leveraging advanced technology to provide highly seamless, incredibly secure, and massively accessible banking experiences.

HDFC Bank is incredibly deeply committed to maintaining the absolute highest possible standards of professional integrity, robust corporate governance, and exceedingly strict regulatory compliance. The financial institution has very aggressively championed advanced digital banking innovations, developing incredibly robust, highly scalable mobile and internet banking platforms that cater exceptionally well to India's rapidly evolving, fast-paced digital economy. Beyond its undeniable, massive commercial success, HDFC Bank is highly actively involved in widespread community development and massive financial inclusion initiatives through its flagship, deeply impactful CSR program, Parivartan. With a truly massive national network of thousands of branches and ATMs, HDFC Bank continues to forcefully drive Indian economic growth and consistently set high benchmarks in the financial sector.`, officeImages: [hdfcOffice1, hdfcOffice2, hdfcOffice3] },
  { id: 18, name: 'ICICI Bank', fullName: 'ICICI Bank Limited', category: 'finance', sector: 'Finance', location: 'Mumbai, Maharashtra', logo: iciciLogo, website: 'https://www.icicibank.com', startedFrom: '1994', founder: 'Industrial Credit and Investment Corporation', employees: '130,000+', workCulture: 'Customer First, Agility, Passion', studentsPlaced: '280+ (Approx.)', description: 'ICICI Bank is an Indian multinational bank and financial services company.', moreInfo: `ICICI Bank Limited is a tremendously leading Indian multinational bank and highly diversified financial services institution headquartered prominently in Mumbai. Originating in 1994 as a wholly-owned corporate subsidiary of the Industrial Credit and Investment Corporation of India—a government-backed, foundational institution for industrial finance—the bank has subsequently grown exponentially to offer incredibly expansive financial services across major retail and massive corporate divisions. ICICI Bank provides a wonderfully wide, comprehensive spectrum of financial products and services, thoroughly including savings and deposit accounts, diverse loans, credit cards, comprehensive insurance, and strategic wealth management. The bank successfully operates a massive, sprawling network of thousands of branches across India and maintains a very significant international footprint.

ICICI Bank has consistently and remarkably been at the absolute forefront of rapid technological innovation within the broader banking sector, aggressively championing digital banking and highly customer-centric digital platforms. The institution heavily leverages advanced data analytics, artificial intelligence, and highly robust enterprise financial frameworks to deliver deeply personalized banking experiences and significantly streamline its complex internal operations. The bank is also incredibly deeply committed to widespread corporate social responsibility, focusing very heavily on improving primary healthcare, advancing elementary education, and fostering sustainable livelihoods through the dedicated ICICI Foundation. With a tremendously strong cultural emphasis on organizational agility, intense passion, and steadfast customer-first values, ICICI Bank remains a highly dominant, influential player.`, officeImages: [iciciOffice1, iciciOffice2, iciciOffice3] },
  { id: 19, name: 'Goldman Sachs', fullName: 'Goldman Sachs Group', category: 'finance', sector: 'Finance', location: 'New York, USA', logo: goldmanSachsLogo, website: 'https://www.goldmansachs.com', startedFrom: '1869', founder: 'Marcus Goldman', employees: '45,000+', workCulture: 'Excellence, Teamwork, Diversity', studentsPlaced: '40+ (Premium)', description: 'Goldman Sachs is a leading global investment banking, securities and investment management firm.', moreInfo: `The Goldman Sachs Group, Inc. is an incredibly leading, massively influential global investment banking, securities, and strategic investment management firm headquartered prominently in New York City. Founded back in 1869 by Marcus Goldman, the firm has painstakingly built a truly formidable, almost unparalleled reputation as one of the most highly prestigious and deeply influential financial institutions in the entire world. Goldman Sachs provides an exceedingly expansive, highly sophisticated array of complex financial services to a very substantial and incredibly diversified global client base that fundamentally includes major multinational corporations, large financial institutions, sovereign governments, and high-net-worth individuals. The firm's core global operations span high-level investment banking, global markets, asset management, and rapidly expanding consumer and wealth management.

Goldman Sachs successfully and masterfully navigates incredibly complex global markets to manage vast, multi-billion-dollar portfolios and proactively provide highly strategic, high-stakes advisory services, standing firmly as a critical, load-bearing pillar in global financial markets and massive macro-economic structuring. The firm is globally renowned for its incredibly intense, unapologetically high-performance organizational culture, consistently attracting many of the absolute brightest, most driven minds in global finance and advanced quantitative analysis. In recent years, Goldman Sachs has significantly increased its strategic focus on technology and advanced engineering, internally developing highly sophisticated algorithmic trading platforms and digital financial tools. Committed strongly to sustainable finance and broad inclusive growth, the firm continually strives to firmly deliver excellence.`, officeImages: [gsOffice1, gsOffice2, gsOffice3] },
  { id: 20, name: 'Morgan Stanley', fullName: 'Morgan Stanley', category: 'finance', sector: 'Finance', location: 'New York, USA', logo: morganStanleyLogo, website: 'https://www.morganstanley.com', startedFrom: '1935', founder: 'Henry Sturgis Morgan', employees: '82,000+', workCulture: 'Integrity, Community Role', studentsPlaced: '30+ (Premium)', description: 'Morgan Stanley is an American multinational investment bank and financial services company.', moreInfo: `Morgan Stanley is a massive, highly prestigious American multinational investment bank and incredibly diversified financial services company based prominently in New York City. Operating successfully in more than 41 different countries globally, the firm was originally founded in 1935 by Henry Sturgis Morgan and Harold Stanley. Morgan Stanley actively and aggressively provides a highly comprehensive, sophisticated range of critical services that explicitly include top-tier investment banking, institutional securities, massive wealth management, and strategic investment management. The firm caters directly to a wonderfully diverse, highly globalized group of clients worldwide, broadly encompassing massive corporations, sovereign governments, institutional investors, and very high-net-worth individuals, significantly helping them raise, manage, and seamlessly distribute vast capital in incredibly complex global markets.

Morgan Stanley consistently, reliably mobilizes enormous sums of capital to comprehensively help its numerous clients successfully achieve their complex financial objectives, proudly standing as an absolutely critical, foundational pillar in broad global financial markets and global macro-economic structuring. The firm is incredibly deeply committed to consistently conducting first-class business in a strictly first-class way, prioritizing absolute integrity, exceptional financial performance, and a very strong, abiding sense of community responsibility. Morgan Stanley heavily leverages highly advanced technological infrastructure and incredibly deep, data-driven market insights to reliably deliver premier, world-class wealth management and institutional securities services. The firm is also a very strong, vocal advocate for highly sustainable investing and workplace diversity, continuously working to create long-term value.`, officeImages: [morganOffice1, morganOffice2, morganOffice3] },

  // Analytics
  { id: 21, name: 'Mu Sigma', fullName: 'Mu Sigma', category: 'analytics', sector: 'Analytics', location: 'Chicago, USA', logo: muSigmaLogo, website: 'https://www.mu-sigma.com', startedFrom: '2004', founder: 'Dhiraj Rajaram', employees: '3,500+', workCulture: 'Curiosity, Impact, Learning', studentsPlaced: '50+ (Approx.)', description: 'Mu Sigma is a prominent decision sciences and big data analytics firm.', moreInfo: `Mu Sigma is a highly prominent, incredibly influential decision sciences and massive big data analytics firm primarily headquartered in Chicago, Illinois, with a truly massive, bustling delivery center located in Bengaluru, India. Founded originally in 2004 by visionary Dhiraj Rajaram, the firm actively enables massive global enterprises to successfully institutionalize highly data-driven decision making and thoroughly transform their entire organizational ecosystems. Mu Sigma provides a very unique, highly potent blend of strategic consulting, applied mathematics, and advanced technology to systematically unpack incredibly complex data insights, significantly helping vast businesses optimize their core operations, massively enhance customer experiences, and aggressively drive sustainable growth. The firm works extensively, day-in and day-out, with Fortune 500 companies across various major sectors.

Mu Sigma is highly renowned globally for its wonderfully distinct, highly structured approach to complex problem-solving, having successfully created a highly unique "Art of Problem Solving" framework that deeply empowers its thousands of data scientists and data analysts to successfully tackle highly multifaceted, deeply entrenched business challenges. The company enthusiastically fosters a vibrant culture of intense intellectual curiosity, continuous rigorous learning, and deeply impactful innovation, rigorously training its massive workforce through highly specialized, extremely demanding internal academies. By continuously developing advanced, proprietary analytics platforms and sophisticated methodologies, Mu Sigma significantly helps large organizations navigate the daunting complexities of massive data streams. The firm unquestionably remains a true pioneer in the analytics industry.`, officeImages: [muSigmaLogo, muSigmaLogo, muSigmaLogo] },
  { id: 22, name: 'Fractal Analytics', fullName: 'Fractal Analytics', category: 'analytics', sector: 'Analytics', location: 'Mumbai, Maharashtra', logo: fractalLogo, website: 'https://fractal.ai', startedFrom: '2000', founder: 'Srikanth Velamakanni', employees: '4,000+', workCulture: 'Care, Integrity, Fun', studentsPlaced: '70+ (Approx.)', description: 'Fractal is one of the most prominent players in the Artificial Intelligence space.', moreInfo: `Fractal Analytics is a tremendously massive, highly influential multinational artificial intelligence and advanced predictive analytics company with sprawling operations globally and impressive dual headquarters located in Mumbai and New York. Founded back in 2000 by Srikanth Velamakanni and Pranay Agrawal, Fractal has rapidly, aggressively emerged as one of the absolutely most prominent, highly respected players in the entire global AI and advanced analytics space. The company's very clear, overarching mission is to fundamentally power every single human decision made in the massive modern enterprise by successfully bringing incredibly deep AI, advanced engineering, and thoughtful design to life. Fractal significantly helps massive Fortune 500 companies drive massive revenue growth, vastly improve operational efficiency, and dramatically enhance customer experiences.

Fractal's incredibly extensive, highly sophisticated portfolio prominently includes specialized, highly advanced AI products and platforms that systematically address vast, deeply entrenched operational challenges, such as advanced healthcare diagnostics, complex revenue growth management, and highly intelligent conversational AI. The company is incredibly deeply committed to a remarkably strong culture of deep care, unyielding integrity, and immense intellectual freedom, consistently attracting absolute top-tier, world-class talent in complex data science, behavioral science, and advanced software engineering. Fractal continuously invests incredibly heavily in bleeding-edge research and development, constantly exploring the very frontiers of generative AI and deep machine learning to deliver highly innovative solutions. Fractal Analytics remains an absolutely vital partner for enterprises.`, officeImages: [fractalLogo, fractalLogo, fractalLogo] },
  { id: 23, name: 'LatentView', fullName: 'LatentView Analytics', category: 'analytics', sector: 'Analytics', location: 'Chennai, Tamil Nadu', logo: latentViewLogo, website: 'https://www.latentview.com', startedFrom: '2006', founder: 'Venkat Viswanathan', employees: '1,000+', workCulture: 'Innovation, Empowerment', studentsPlaced: '40+ (Approx.)', description: 'LatentView provides digital analytics and data engineering to Fortune 500 companies.', moreInfo: `LatentView Analytics is a highly robust, incredibly globally respected digital analytics capability firm that consistently provides highly robust data engineering, deeply advanced predictive modeling, and highly actionable, data-driven insights primarily to massive Fortune 500 companies. Founded originally in 2006 by visionary Venkat Viswanathan, the company specializes intensely in helping large global organizations seamlessly harness the immense power of big data and highly advanced analytics to successfully drive comprehensive, end-to-end business transformation. LatentView's expansive services broadly span across complex business analytics, massive data engineering, highly customized digital solutions, and strategic consulting, catering primarily and very successfully to the global technology, consumer packaged goods (CPG), retail, and highly complex financial services sectors. The firm excels remarkably in unearthing hidden patterns.

LatentView highly actively helps its massive corporate clients successfully realize their ambitious digital transformation visions by fully leveraging incredibly comprehensive data streams to drive significantly better, vastly more intuitive business decisions. The company is broadly characterized by an incredibly strong, deeply rooted culture of technological innovation, deep employee empowerment, and absolute technical excellence, continuously expanding its incredibly sophisticated capabilities in deep machine learning and advanced artificial intelligence. LatentView operates incredibly successfully globally, with a very significant, expanding presence in North America, Europe, and Asia, consistently delivering extremely high-impact solutions through a deeply, remarkably collaborative client approach. Through its massive focus on industry thought leadership, LatentView Analytics continues to be trusted globally.`, officeImages: [latentViewLogo, latentViewLogo, latentViewLogo] },

  // Telecom
  { id: 24, name: 'Jio', fullName: 'Reliance Jio', category: 'telecom', sector: 'Telecom', location: 'Navi Mumbai, Maharashtra', logo: jioLogo, website: 'https://www.jio.com', startedFrom: '2007', founder: 'Mukesh Ambani', employees: '80,000+', workCulture: 'Speed, Agility, Customer Focus', studentsPlaced: '400+ (Approx.)', description: 'Jio is an Indian telecommunications company and a subsidiary of Jio Platforms.', moreInfo: `Reliance Jio Infocomm Limited, universally and commonly known simply as Jio, is an absolutely premier, massively dominant Indian telecommunications company and a highly crucial subsidiary of Jio Platforms, headquartered prominently in Navi Mumbai, Maharashtra. Launched commercially with massive fanfare in 2016 by billionaire Mukesh Ambani, Jio operates a truly massive, incredibly expansive national LTE/5G network with comprehensive, near-ubiquitous coverage across all 22 official telecom circles in India. Jio radically, fundamentally transformed the entire Indian telecom landscape by suddenly offering incredibly high-speed data and entirely free voice calling at truly unprecedented, massively disruptive rates, effectively democratizing broad digital access and successfully bringing high-speed internet to many hundreds of millions of people. The company offers a wide ecosystem.

Jio's massive, overarching corporate mission is to relentlessly drive India's sweeping digital revolution by continuously providing highly affordable, incredibly high-quality connectivity and a massive, comprehensive suite of highly advanced digital applications. The company has incredibly aggressively rolled out its massive True 5G network, setting incredible global benchmarks in incredibly fast network deployment speed and massive scale. Beyond pure telecommunications, Jio is heavily, aggressively investing in highly emerging technologies like advanced artificial intelligence, highly secure blockchain, and the complex Internet of Things (IoT) to thoroughly build a truly robust digital infrastructure for the future. With an intense culture focused on extreme speed, Jio continues to lead completely.`, officeImages: [jioLogo, jioLogo, jioLogo] },
  { id: 25, name: 'Airtel', fullName: 'Bharti Airtel', category: 'telecom', sector: 'Telecom', location: 'New Delhi, Delhi', logo: airtelLogo, website: 'https://www.airtel.in', startedFrom: '1995', founder: 'Sunil Bharti Mittal', employees: '17,000+', workCulture: 'Alive, Inclusive, Respectful', studentsPlaced: '150+ (Approx.)', description: 'Airtel is a leading global telecommunications company with operations in 18 countries across Asia and Africa.', moreInfo: `Bharti Airtel Limited, universally and commonly known simply as Airtel, is an absolutely premier, highly esteemed Indian global telecommunications company headquartered prominently in New Delhi. Founded originally in 1995 by visionary Sunil Bharti Mittal, Airtel operates incredibly successfully across 18 distinct countries heavily spanning South Asia and vast parts of Africa, proudly maintaining a truly massive, incredibly expansive global footprint. The company provides a remarkably comprehensive, highly robust suite of advanced telecommunications services, prominently including incredibly high-speed 4G and 5G mobile services, highly reliable fixed-line broadband, extensive digital television, and deeply comprehensive enterprise business solutions. Airtel has consistently been a truly pioneering, deeply driving force in the massive Indian telecom sector, consistently driving major technological innovation.

Ranked incredibly consistently among the absolute top mobile service providers globally by total subscriber base, Airtel consistently delivers highly dynamic, incredibly reliable, and very deeply integrated digital services. The company remains incredibly highly focused on consistently providing easily accessible, robust telecom infrastructure, currently aggressively rolling out its incredibly fast 5G network to deeply empower both individual consumers and massive global enterprises alike. Airtel is also incredibly deeply committed to widespread corporate social responsibility, actively spearheading numerous impactful initiatives in broad education and deep community development entirely through the highly active Bharti Foundation. With a tremendously strong corporate culture of deep inclusivity, absolute respect, and technological excellence, Airtel continues to build robust networks.`, officeImages: [airtelLogo, airtelLogo, airtelLogo] },

  // Others
  { id: 26, name: 'Jaro Education', fullName: 'Jaro Education', category: 'others', sector: 'Others', location: 'Mumbai, Maharashtra', logo: jaroLogo, website: 'https://www.jaroeducation.com', startedFrom: '2009', founder: 'Sanjay Salunkhe', employees: '800+', workCulture: 'Dynamic, Growth-oriented', studentsPlaced: '120+ (Approx.)', description: 'Jaro Education is India’s most trusted online higher education company.', moreInfo: `Jaro Education is unquestionably India's absolute most trusted, highly reputable online higher education company, fundamentally and highly successfully bridging the massive, growing gap between traditional academia and modern, highly demanding industry requirements. Founded back in 2009 by the visionary Dr. Sanjay Salunkhe, the company specializes incredibly deeply in providing highly premium executive education programs, fully online master's degrees, and highly specialized, tremendously valuable certification courses. By successfully partnering with absolutely leading, highly prestigious universities and premier educational institutes globally, Jaro equips ambitious working professionals and highly aspiring corporate leaders with incredibly highly curated, absolutely top-tier management and technical skills. The company's incredibly innovative learning platforms and highly effective hybrid educational models offer massive flexibility.

Jaro Education is incredibly deeply committed to thoroughly transforming corporate careers by consistently delivering exceptionally high-quality, intensely industry-relevant curricula that vastly, significantly accelerate corporate trajectories in incredibly highly competitive global markets. The company aggressively leverages highly advanced educational technologies and deeply innovative pedagogical methodologies to effectively ensure an incredibly engaging, deeply impactful, and highly memorable learning experience. With a truly vast, highly active alumni network and incredibly strong, deeply entrenched corporate connections, Jaro incredibly actively facilitates seamless career transitions and massive advancements for its thousands of learners. Cultivating a wonderfully dynamic, incredibly growth-oriented internal work culture, Jaro Education absolutely continues to be a highly pioneering, incredibly massive force in the booming Indian ed-tech space.`, officeImages: [jaroLogo, jaroLogo, jaroLogo] },
  { id: 27, name: 'Byju\'s', fullName: 'Think and Learn Pvt Ltd', category: 'others', sector: 'Others', location: 'Bengaluru, Karnataka', logo: byjusLogo, website: 'https://www.byjus.com', startedFrom: '2011', founder: 'Byju Raveendran', employees: '10,000+', workCulture: 'Fast-paced, Impactful', studentsPlaced: '200+ (Approx.)', description: 'Byju\'s is a global ed-tech company, providing highly adaptive, engaging and effective learning programs.', moreInfo: `Think and Learn Pvt Ltd, operating as Byju's, is a global ed-tech company providing adaptive, engaging, and highly effective learning programs. Founded in 2011, it skyrocketed to become one of the most prominent online learning platforms.\n\nCreating vastly personalized educational programs using deep interactive animations, Byju's systematically breaks down complex concepts for students, radically transforming modern learning ecosystems.`, officeImages: [byjusLogo, byjusLogo, byjusLogo] },
  { id: 28, name: 'Amazon', fullName: 'Amazon.com, Inc.', category: 'it', sector: 'IT & Software', location: 'Seattle, USA', logo: amazonLogo, website: 'https://www.amazon.in', startedFrom: '1994', founder: 'Jeff Bezos', employees: '1,500,000+', workCulture: 'Customer Obsession, Innovation, Bias for Action', studentsPlaced: '80+ (Approx.)', description: 'Amazon is a globally reputed e-commerce, cloud computing, and AI multinational technology company.', moreInfo: `Amazon.com, Inc. is an incredibly globally reputed, massively dominant American multinational technology company extremely heavily focused on global e-commerce, incredibly massive cloud computing, digital media streaming, and highly advanced artificial intelligence. Founded originally in 1994 by visionary Jeff Bezos in a small garage in Bellevue, Washington, the company initially started modestly as an online marketplace solely for books before rapidly, incredibly aggressively expanding into a truly vast, almost unimaginably large array of product categories. Today, Amazon is an absolute juggernaut of the modern tech era, successfully operating an unparalleled, incredibly sophisticated global logistics and rapid fulfillment network. The company’s massive cloud computing division, Amazon Web Services (AWS), is undoubtedly the world's most comprehensive cloud platform.

Amazon adheres incredibly strictly to four highly pivotal, foundational principles: extreme, almost obsessive customer obsession, incredibly deep passion for continuous invention, completely unwavering commitment to absolute operational excellence, and highly visionary, incredibly bold long-term thinking. The company is continuously, relentlessly pioneering highly disruptive innovations such as incredibly advanced voice-activated technology (Alexa), totally cashier-less grocery stores (Amazon Go), and amazingly advanced, highly sophisticated robotics operating seamlessly in its massive fulfillment centers. Amazon is also incredibly deeply committed to massive global sustainability officially through its ambitious Climate Pledge, aggressively aiming to be completely net-zero carbon entirely across its massive business by 2040. With a truly colossal, incredibly diverse global workforce, Amazon continues to deeply influence global commerce.`, officeImages: [amazonLogo, amazonLogo, amazonLogo] },
  { id: 29, name: 'IBM', fullName: 'International Business Machines Corporation', category: 'it', sector: 'IT & Software', location: 'Armonk, USA', logo: ibmLogo, website: 'https://www.ibm.com', startedFrom: '1911', founder: 'Charles Ranlett Flint', employees: '280,000+', workCulture: 'Innovation, Trust, Personal Responsibility', studentsPlaced: '120+ (Approx.)', description: 'IBM is a globally integrated enterprise and a major player in cloud computing and AI.', moreInfo: `International Business Machines Corporation (IBM) is an American multinational technology corporation headquartered in Armonk, New York, with operations in over 171 countries. Founded in 1911 by Charles Ranlett Flint as the Computing-Tabulating-Recording Company (CTR), it was renamed "International Business Machines" in 1924. IBM is globally known for producing and selling computer hardware, middleware, and software, as well as providing hosting and consulting services in areas ranging from mainframe computers to nanotechnology. The company is a research powerhouse, holding the record for most U.S. patents generated by a business for 29 consecutive years.\n\nToday, IBM is heavily focused on hybrid cloud and artificial intelligence, helping enterprises transform their businesses through advanced technology and services. The IBM Cloud platform, combined with its Watson AI capabilities, allows organizations to innovate efficiently and securely. IBM continues to lead in quantum computing research and sustainability, driving significant advancements across various industries such as healthcare, finance, and logistics. With a massive global workforce, IBM cultivates a strong culture of innovation, deep trust, and personal responsibility, empowering its clients and contributing broadly to societal progress.`, officeImages: [ibmLogo, ibmLogo, ibmLogo] },
  { id: 30, name: 'Oracle', fullName: 'Oracle Corporation', category: 'it', sector: 'IT & Software', location: 'Austin, USA', logo: oracleLogo, website: 'https://www.oracle.com', startedFrom: '1977', founder: 'Larry Ellison, Bob Miner, Ed Oates', employees: '160,000+', workCulture: 'Customer Success, Innovation, Leadership', studentsPlaced: '90+ (Approx.)', description: 'Oracle is a multinational computer technology corporation specializing in enterprise software and cloud systems.', moreInfo: `Oracle Corporation is an American multinational computer technology corporation headquartered in Austin, Texas. Founded in 1977 by Larry Ellison, Bob Miner, and Ed Oates, Oracle initially established itself as a pioneer in relational database management systems. Today, the company is one of the largest software companies in the world by revenue and market capitalization, providing a comprehensive and fully integrated stack of cloud applications and platform services. Oracle's core products include its flagship Oracle Database software, enterprise resource planning (ERP) software, human capital management (HCM) software, and supply chain management (SCM) software, all designed to help businesses optimize their operations globally.\n\nOracle's transition to the cloud has been a massive strategic focus, with Oracle Cloud Infrastructure (OCI) providing high-performance computing power, storage, and networking capabilities for modern enterprise workloads. The company is deeply invested in artificial intelligence, autonomous database technology, and advanced data analytics, empowering clients to extract maximum value from their data securely. Known for its intense focus on customer success, strong leadership, and continuous innovation, Oracle partners with major organizations across diverse sectors, playing a critical role in shaping the modern enterprise technology landscape and driving digital transformation worldwide.`, officeImages: [oracleLogo, oracleLogo, oracleLogo] }
];

const ITEMS_PER_PAGE = 10;
const SECTORS = ['All Sectors', 'IT & Software', 'Core Engineering', 'Consulting', 'Finance', 'Analytics', 'Telecom', 'Others'];

const superEnlargedLogos = ['Capgemini', 'Microsoft', 'Bosch', 'Goldman Sachs', 'Mu Sigma', 'Fractal Analytics', 'Jio', 'IBM', 'Amazon'];
const doubleEnlargedLogos = ['KPMG', 'PwC', 'Siemens'];
const extraLargeLogos = ['LatentView'];
const largeLogos = ['HDFC Bank'];
const smallLogos = [];
const increaseLittleLogos = ['TCS', 'Infosys', 'Cognizant', 'SAP', 'Accenture', 'Deloitte', 'Airtel', 'Google'];
const increaseDoubleLogos = ['Byju\'s', 'Morgan Stanley', 'Tata Motors', 'Wipro'];
const decreaseLittleLogos = [];

export default function Companies({ user, onBack, onOpenPlacements, onOpenLogin, onOpenNoticeBoard, onOpenCompanyOffers, onOpenCompanyStudy, initialCompany, onOpenPlacementsForCompany, onOpenProfile }) {
  const [activeCategory, setActiveCategory] = useState('all');
  const [search, setSearch] = useState('');
  const [sector, setSector] = useState('All Sectors');
  const [page, setPage] = useState(1);
  const [showLoginPopup, setShowLoginPopup] = useState(false);
  const [selectedCompany, setSelectedCompany] = useState(initialCompany || null);

  const activeCompany = selectedCompany ? COMPANIES.find(c => c.id === selectedCompany.id) : null;
  const totalPages = 10;

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [selectedCompany]);

  const handleViewDetails = (company) => {
    if (!user) {
      setShowLoginPopup(true);
    } else {
      setSelectedCompany(company);
    }
  };

  const filtered = COMPANIES.filter(c => {
    const matchSearch = c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.sector.toLowerCase().includes(search.toLowerCase());
    const matchSector = sector === 'All Sectors' || c.sector === sector;
    return matchSearch && matchSector;
  });

  const handleNavClick = (e, path, action) => {
    e.preventDefault();
    window.history.pushState({}, '', path);
    if (action) action();
  };

  return (
    <div className="companies-page">
      <Navbar
        activePage="companies"
        onOpenLogin={onOpenLogin}
        onOpenHome={onBack}
        onOpenCompanies={() => { setSelectedCompany(null); window.scrollTo(0, 0); }}
        onOpenPlacements={onOpenPlacements}
        onOpenNoticeBoard={onOpenNoticeBoard}
        onOpenProfile={onOpenProfile}
        user={user}
        useEmojiLogo={true}
      />

      <div className="co-body">

        {activeCompany ? (
          <CompanyDetails 
          company={activeCompany} 
          onBack={() => setSelectedCompany(null)} 
          onOpenCompanyOffers={() => onOpenCompanyOffers(activeCompany)} 
          onOpenCompanyStudy={() => onOpenCompanyStudy(activeCompany)} 
          onViewAllPlacements={() => onOpenPlacementsForCompany(activeCompany.name)}
        />
        ) : (
          <main className="co-main">

            {/* Header row */}
            <div className="co-header">
              <div>
                <h1 className="co-title">Recruiters</h1>
                <p className="co-subtitle">Explore our top recruiting companies and discover opportunities that match your career goals.</p>
              </div>
              <div className="co-controls">
                <div className="co-search">
                  <span className="co-search-icon">🔍</span>
                  <input
                    type="text"
                    placeholder="Search Company..."
                    value={search}
                    onChange={e => { setSearch(e.target.value); setPage(1); }}
                  />
                </div>
                <select
                  className="co-sector-select"
                  value={sector}
                  onChange={e => setSector(e.target.value)}
                >
                  {SECTORS.map(s => <option key={s}>{s}</option>)}
                </select>
              </div>
            </div>

            {/* Company grid */}
            <div className="co-grid">
              {filtered.map(company => (
                <div key={company.id} className="co-card">
                  <div className="co-logo-box">
                    <img 
                      src={company.logo} 
                      alt={`${company.name} logo`} 
                      className={`co-company-logo ${
                        superEnlargedLogos.includes(company.name) ? 'super-enlarged-logo' : 
                        doubleEnlargedLogos.includes(company.name) ? 'double-enlarged-logo' : 
                        extraLargeLogos.includes(company.name) ? 'extra-enlarged-logo' : 
                        largeLogos.includes(company.name) ? 'enlarged-logo' : 
                        smallLogos.includes(company.name) ? 'reduced-logo' : ''
                      } ${decreaseLittleLogos.includes(company.name) ? 'decrease-little' : ''
                      } ${increaseLittleLogos.includes(company.name) ? 'increase-little' : ''
                      } ${increaseDoubleLogos.includes(company.name) ? 'increase-double' : ''
                      } ${(!increaseLittleLogos.includes(company.name) && !increaseDoubleLogos.includes(company.name) && !decreaseLittleLogos.includes(company.name)) ? 'increase-thrice' : ''}`} 
                    />
                  </div>
                  <div className="co-card-body">
                    <div className="co-card-name">{company.name}</div>
                    <div className="co-card-sector">{company.sector}</div>
                    <div className="co-card-location">📍 {company.location}</div>
                    <button className="co-view-btn" onClick={() => handleViewDetails(company)}>View Details →</button>
                  </div>
                </div>
              ))}
              {filtered.length === 0 && (
                <div className="co-empty">No companies found matching your search.</div>
              )}
            </div>



          </main>
        )}
      </div>


      {/* Footer */}
      <footer className="co-footer">
        <span>© 2025 PRMIT&R, Badnera. All rights reserved.</span>
        <span>Placement Management System →</span>
      </footer>

      {/* Custom Login Popup */}
      {showLoginPopup && (
        <div className="co-modal-overlay">
          <div className="co-modal-card">
            <div className="co-modal-icon-container">
              <i className="fas fa-lock"></i>
            </div>
            <h3 className="co-modal-title">Login Required</h3>
            <p className="co-modal-desc">
              Please login first to view detailed company information and access placement resources.
            </p>
            <div className="co-modal-actions">
              <button 
                className="co-modal-btn co-modal-btn-cancel"
                onClick={() => setShowLoginPopup(false)} 
              >
                Cancel
              </button>
              <button 
                className="co-modal-btn co-modal-btn-primary"
                onClick={() => { setShowLoginPopup(false); if(onOpenLogin) onOpenLogin(); }} 
              >
                Go to Login
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}







